server:
  port: 1111
  context-path: /customer
  error:
    whitelabel:
      enabled: true
 
spring:
  application:
    name: customer-service
    


# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: false
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full



# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

      
   