server:
  port: 1111
  context-path: /customer-service
  error:
    whitelabel:
      enabled: false
 
spring:
  application:
    name: customer-service
    
management:
  security:
    enabled: false
    
security:
  basic:
    enabled: false

eureka:
  instance:
    lease-expiration-duration-in-seconds: 2 
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://localhost:8761/eureka/}
     
  
    
# To disable Hystrix in Feign
feign:
  hystrix:
    enabled: false
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        

ribbon:
  ReadTimeout: 30000

# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

      
   